name: Deploy Lambda
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '18' # Adjust this to match your project's Node.js version

      - name: Install dependencies
        run: npm install
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '18' # Adjust this to match your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Zip and compress files
        run: |
          zip -r deployment-package.zip ./*
          gzip -9 -c deployment-package.zip > deployment-package.gz

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name testTakerApp --zip-file fileb://deployment-package.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
